server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/BlanFT/microservicios
          search-paths: config-data

  application:
    name: microservice-server

